name: publish-package
on:
  release:
    types: [published]
jobs:
  publish-package-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      
